### PR TITLE
Before the remote script does anything, get a sanity-check hash from it.

### PR DESCRIPTION
**Pull request by countingpine**
This ensures that:
- the script is running
- the requested hash algorithm is available on the remote host
- the filename string has been received/decoded correctly

### CODE REVIEW

**Comment by vog** [comment]
Thanks a lot for your contribution. I like the idea and would love to include it. This is the result of my review:

* I'd like to have a variable "sanity_digest" also in the remote script, to make it more readable and clear that this corresponds to the "sanity_digest" in the main script.
* `io.out_stream.flush()` is a bit hacky, as the whole purpose of the `IOCounter` class is that we don't sidestep it to access the streams directly.
  * Proposal: If the call to `flush()` is really necessary, we should do it consequently on each write. So  `IOCounter.write()` should perform the flush automatically on each call. Please provide a separate commit for that (and if you like, a separate pull request). It would be great if you could perform a simple test run to measure the performance impact (which I guess would be close to zero, but better measure than guess).
* Feel free to add yourself to the list below the copyright line.

**Comment by countingpine** [comment]
Hi vog, thanks for your review!

I don't know if `flush()` is strictly necessary - it seems to work for me without it, but I'm not an expert, and I don't know how to be sure that it would work in any situation (e.g. different OS's / Python versions).  

(That said, there may already be places in the code that assume IO flushes properly by itself, so this might not break anything either way..)

Adding an explicit `flush()` to `IOCounter.write` might be the best compromise.  Two flushes per changed block from the local script is probably fine, but I will try and get round to doing some sort of test.

I'll remove the hackish `io.out_stream.flush()` from this PR. I don't feel I can make any guarantees over whether the script will hang without adding modifying `IOCounter.write` though, so should this one be committed on its own?

You're right, it makes sense to have a `sanity_digest` variable in both scripts.  I will also add my name.

**Comment by countingpine** [comment]
I've committed the changes.

The last commit adds the `flush()` into `io.write()`.  I was wondering if something more intelligent would be better, but I tested the changes over a wifi connection between two computers, and the difference wasn't really measurable compared to the natural variance between runs - it often had the marginally shorter runtime, even with smaller block sizes.  So I don't think it should cause any concerns with performance.

**Comment by vog** [comment]
Looks great. Thanks!

**Comment by vog** [comment]
To anyone involved in this issue, please see #16 "Future of bscp".

**Pull request merged**
